- hosts: localhost
  become: true
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    source_key_public: "./.ssh/id_ed25519.pub"
    dest_key_public: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
  tasks:
  - import_tasks: tasks/zsh.yml
    tags: zsh
  - import_tasks: tasks/dotfiles.yml
  - import_tasks: tasks/ssh.yml
  - import_tasks: tasks/homebrew.yml
  - import_tasks: tasks/vim.yml
    tags:
      - vim
  - import_tasks: tasks/macos.yml