- hosts: localhost
  become: true
  tasks:
  - name: Install Zsh Already installed on MacOS
    apt: name=zsh
    tags:
      - zsh
  - name: Change shell to zsh
    shell: chsh -s `which zsh`
    tags:
      - zsh
      - task
  - name: Install ohmyzsh
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    tags:
      - zsh
  - name: Install the zsh plugin autosuggestions
    ansible.builtin.git:
      repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: '~/.oh-my-zsh/custom/plugins/zsh-autosuggestions'
      tags:
        - zsh
  - name: Install homebrew packages
    become: false
    community.general.homebrew:
      name:
        - nvm
        - httpie
    tags:
      - homebrew