- hosts: localhost
  become: true
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    source_key_public: "./.ssh/id_ed25519.pub"
    dest_key_public: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
  tasks:
  - name: Install homebrew packages
    become_user: "{{ user }}"
    homebrew:
      name:
        - nvm
        - httpie
        - tldr
    tags:
      - homebrew
  - import_tasks: tasks/zsh.yml
    tags: zsh
  - import_tasks: tasks/dotfiles.yml
  - import_tasks: tasks/ssh.yml
  - import_tasks: tasks/apps.yml
  - import_tasks: tasks/navigation.yml
    tags:
      - navigation
