- hosts: localhost
  become: true
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    source_key_public: "./.ssh/id_ed25519.pub"
    dest_key_public: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
  tasks:
  - name: Change shell to zsh
    shell: chsh -s `which zsh`
    tags:
      - zsh

  - name: Install ohmyzsh
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    tags:
      - zsh
  - name: Install the zsh plugin autosuggestions
    ansible.builtin.git:
      repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: '~/.oh-my-zsh/custom/plugins/zsh-autosuggestions'
    tags:
      - zsh
  - name: Install homebrew packages
    become_user: "{{ user }}"
    community.general.homebrew:
      name:
        - nvm
        - httpie
    tags:
      - homebrew
  - name: copy ssh keys
    include: tasks/ssh.yml
  - name: copy and stow dotfiles
    include: tasks/dotfiles.yml
  - name: Install MacOS Apps
    include: tasks/apps.yml
