- hosts: localhost
  become: true
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    source_key_public: "./.ssh/id_ed25519.pub"
    dest_key_public: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
  tasks:
  - name: Install homebrew packages
    become_user: "{{ user }}"
    community.general.homebrew:
      name:
        - nvm
        - httpie
    tags:
      - homebrew
  - name: Setup Zsh
    tags: zsh
    include: tasks/zsh.yml
  - name: copy and stow dotfiles
    include: tasks/dotfiles.yml
  - name: copy ssh keys
    include: tasks/ssh.yml
  - name: Install MacOS Apps
    include: tasks/apps.yml
