- name: Installing stow
  become_user: "{{ user }}"
  homebrew:
    name:
      - stow
  tags:
    - dotfiles
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/dadeef/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - dotfiles
- name: Stow dotfiles
  shell: rm $HOME/.zshrc && cd $HOME/.dotfiles && stow home # remove auto=generated .zshrc to prevent stow conflicts
  tags:
    - dotfiles