- name: Install homebrew packages
  become_user: "{{ user }}"
  homebrew:
    name:
      - tmux
      - fzf
  tags:
    - navigation

- name: Install Amethyst Window Manager
  become_user: "{{ user }}"
  homebrew_cask:
    name: amethyst
    state: present