- name: Ensure .ssh directory exists.
  become_user: "{{user}}"
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - ssh
- name: Install ssh private key
  become_user: "{{user}}"
  copy:
    src: "{{ source_key}}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - ssh
- name: Install ssh public key
  become_user: "{{user}}"
  copy:
    src: "{{ source_key_public }}"
    dest: "{{ dest_key_public }}"
    mode: 0600
  tags:
    - ssh
- name: Adds SSH authorized key for user account
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    # key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
  tags:
    - ssh

# Old School key stuff for Azure compatibility

- name: Copy ssh config so we can use the right ssh key depending on the domain
  become_user: "{{user}}"
  copy:
    src: "{{ source_config}}"
    dest: "{{ dest_config }}"
    mode: 0600
  tags:
    - ssh
    - old-skool

- name: Install ssh old skool private key
  become_user: "{{user}}"
  copy:
    src: "{{ source_key_old_skool}}"
    dest: "{{ dest_key_old_skool }}"
    mode: 0600
  tags:
    - ssh
    - old-skool
- name: Install ssh old skool public key
  become_user: "{{user}}"
  copy:
    src: "{{ source_key_public_old_skool }}"
    dest: "{{ dest_key_public_old_skool }}"
    mode: 0600
  tags:
    - ssh
    - old-skool
- name: Adds SSH old skool authorized key for user account
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  tags:
    - ssh
    - old-skool
