- name: Install yabai & skhd
  become_user: davidderen
  homebrew:
    name:
      - koekeishiya/formulae/yabai
      - koekeishiya/formulae/skhd

- name: start yabai & skhd
  become_user: davidderen
  shell: "/usr/local/bin/brew services start {{ item }}"
  with_items:
  - yabai
  - skhd